name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Publish Serverless Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: vercel
          path: out
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Restore CI Cache
        uses: actions/cache@v2.1.6
        id: cache-restore
        with:
          path: node_modules
          key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies if Cache Miss
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: yarn --frozen-lockfile
      - name: Build code for Vercel
        run: yarn vercel-build
      - name: Push new code
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo -e "\n# Remove any old files in the dist folder"
          rm -rfv out/api/*
          rm -rfv out/public/*

          echo -e "\n# Move the generated docs to the newly-checked-out repo, to be committed and pushed"
          rsync -vaI api/ out/api
          rsync -vaI public/ out/public

          echo -e "\n# Commit and push"
          cd out
          git add --all .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "build: vercel build for ${GITHUB_SHA}" || true
          git push origin vercel

  PublishCommands:
    name: Publish Application Commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Restore CI Cache
        uses: actions/cache@v2.1.6
        id: cache-restore
        with:
          path: node_modules
          key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies if Cache Miss
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: yarn --frozen-lockfile
      - name: Publish Application Commands
        run: yarn update-slashies
        env:
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_APPLICATION_SECRET: ${{ secrets.DISCORD_APPLICATION_SECRET }}
